GPSR_RANGE_OBSERVEモードの削除
ut-issl/c2a-aobc pull request #248
Opened 2023-10-20 12:31 UTC by t-hosonuma

## Issue
- https://github.com/ut-issl/c2a-aobc/issues/157

## 詳細
GPSR_RANGE_OBSERVEモードをモードリストから削除

## 検証結果
### ビルドチェック (どちらもチェック)
- [x] SILSでのビルドチェックに通った(CIで確認)
- [x] vMicroでのビルドチェックに通った

### 動作確認チェック (いずれかをチェック)
- [ ] SILSでアルゴリズムが想定通りに動いた
- [ ] 実機でアルゴリズムが想定通りに動いた
- [ ] (テレコマ試験の場合)コマンドファイルを使った試験をパスした

### 試験結果詳細記述場所 or 詳細ログ保存場所へのリンク
- TBD

## 補足
NA

2024-01-18 19:41 UTC, 200km approved these changes
問題ないです。

2024-01-29 08:46 UTC, 200km requested changes

2024-01-29 08:46 UTC, 200km commented on src/src_user/Applications/UserDefined/AOCS/aocs_mode_manager.c
> -  if ((current_mode != MD_MODEID_FINE_THREE_AXIS) && (current_mode != MD_MODEID_GPSR_RANGE_OBSERVE)) return;
[MUST] よくみたらここ全て消すのはまずいですね。FINE_THREE_AXISは残してください。

2024-02-01 08:49 UTC, 200km approved these changes

2024-02-01 10:12 UTC, t-hosonuma commented
Approve頂いた＆V-microビルドが通ったのでマージします

2024-02-01 10:14 UTC, merged